version: '3.1'
#
services:

  db:
    image: gpmidi/bacula-catalog:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
#
  bacula-dir:
    image: gpmidi/bacula-director:latest
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on:
      - db
    ports:
      - "9101:9101"
#
  bacula-sd:
    image: gpmidi/bacula-storage:latest
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - "9103:9103"
#
  bacula-fd:
    image: gpmidi/bacula-client:latest
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
      - db
    volumes:
      - ./etc:/opt/bacula/etc:ro
    ports:
      - "9102:9102"
#
  baculum-api:
    image: gpmidi/baculum-api:latest
    restart: unless-stopped
    depends_on:
      - db
      - bacula-dir
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - "9096:9096"

#
  baculum-web:
    image: gpmidi/baculum-web:latest
    restart: unless-stopped
    depends_on:
      - baculum-api
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - "9095:9095"

#volumes:
#  pgdata:
