#!/bin/bash
set -e 
set -x

echo "Debug info..."
date
pwd
env

echo "Building..."

docker build \
    --build-arg SOURCE_COMMIT \
    --build-arg BACULA_KEY \
    --build-arg BACULA_VERSION \
    --build-arg EMAIL \
    --build-arg EL_VERSION \
    --build-arg SOURCE_BRANCH \
    --build-arg SOURCE_COMMIT \
    --build-arg COMMIT_MSG \
    --build-arg IMAGE_NAME \
    --build-arg DOCKER_TAG \
    --build-arg DOCKERFILE_PATH \
    --build-arg DOCKER_REPO \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" \
    .

echo "Build ok..."

exit 0
