#!/bin/bash
docker build \
    --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" \
    --build-arg BACULA_KEY="$BACULA_KEY" \
    --build-arg BACULA_VERSION="$BACULA_VERSION" \
    --build-arg EMAIL="$EMAIL" \
    --build-arg SOURCE_BRANCH="$SOURCE_BRANCH" \
    --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" \
    --build-arg COMMIT_MSG="${COMMIT_MSG}" \
    -f "${DOCKERFILE_PATH}" \
    -t "${IMAGE_NAME}" \
    .
exit 0
